---
- name: Installation domain controler
  hosts: domain_server
  gather_facts: false

  pre_tasks:
#    - name: Installer mise à jour
#      ansible.windows.win_updates:
#        reboot: no
#      register: update_res

#    - name: Redemarrer
#      ansible.windows.win_reboot:
#      when: update_res.reboot_required

    - name: Definir IP DNS
      win_dns_client:
        adapter_names: '*'
        ipv4_addresses:
        - 192.168.1.80

    - name: Modifier le nom d'hôte
      win_hostname:
        name: DC1
      register: res

    - name: Redemarer
      win_reboot:
      when: res.reboot_required

#    - name: Mise à jour serveur
#      win_updates:
#        category_names:
#          - SecurityUpdates
#          - CriticalUpdates
#          - Application
#          - DefinitionUpdates
#          - Updates
#        whitelist:
#          - KB4093120
#      reboot: yes
#      reboot_timeout: 420

  tasks:
    - name: Install AD DS
      win_feature:
          name: AD-Domain-Services
          state: present
          include_sub_features: yes
          include_management_tools: yes
      register: install_ADDS

    - name: Redemarer si necessaire
      win_reboot:
        msg: "Le serveur a redemarré..."
      when: install_ADDS.reboot_required   

    - name: Install DNS
      win_feature:
        name: DNS
        state: present
        include_management_tools: yes
      register: win_feature_dns

    - name: Redemarer si necessaire
      win_reboot:
        msg: "Le serveur a redemarré..."
      when: win_feature_dns.reboot_required 

    - name: Créer un nouveau domaine dans une nouvelle forêt
      win_domain:
        dns_domain_name: lab.local
        safe_mode_password: Jesuislenouveau2b&}
#        create_dns_delegation: no
#        database_path: C:\Windows\NTDS
#        domain_mode: WinThreshold
#        domain_netbios_name: TUBIE
#        forest_mode: WinThreshold
#        sysvol_path: C:\Windows\SYSVOL
      register: domain_install

    - name: Redemarer si necessaire
      win_reboot:
        msg: "Le serveur a redemarré..."
        reboot_timeout_sec: 3600
        shutdown_timeout_sec: 3600
      when: domain_install.reboot_required

#    - name: Stop pendant 30s et redemarre
#      ansible.builtin.wait_for:
#      timeout: 30     

    - name: Créer un Admin du domaine
      win_domain_user:
        name: AdminDC
        password: Jesuislenouveau2b&}
        state: present
        groups:
          - Admins du domaine

  post_tasks:
    - name: Créer UO
      community.windows.win_domain_ou:
        name: "{{ item }}"
        state: present
      loop:
        - INFORMATIQUE
        - COMMERCIALE
        - INFIRMIER

    - name: Créer les groupes d'utilisateurs
      ansible.windows.win_group:
        name: "{{ item }}"
        state: present
      loop:
        - informatique
        - commerciale
        - infirmier  
